*  simulate N-variate normal variables with a given covariance matrix V0

In [31]:
import numpy as np
import scipy.linalg as la      # we need the package to compute the Cholesky decomposition

np.random.seed(1234)         # so that the random numbers will be the same each time running the program

N = 3
V0 = np.array([[1, 0.1, 0.3], 
               [0.2, 2, 0.5], 
               [0.3, 0.5, 3]])

L1 = la.cholesky(V0)             # Cholesky decomposition:  V0 = L1'*L1

L = L1.T                         # V0 = L*L',  L=L1'
e = np.random.randn(3,1)   
Y = np.matmul(L,e)              # Y = L*e,  a draw from normal with covariance matrix V0

V = np.matmul(L1.T,L1)              #   verify V0 = L1'*L1

print (V0)      
print(L)
print (V)      
print(' a draw from normal with covariance matrix V0  \n')
print(Y)

[[1.  0.1 0.3]
 [0.2 2.  0.5]
 [0.3 0.5 3. ]]
[[1.         0.         0.        ]
 [0.1        1.4106736  0.        ]
 [0.3        0.33317417 1.67301972]]
[[1.  0.1 0.3]
 [0.1 2.  0.5]
 [0.3 0.5 3. ]]
 a draw from normal with covariance matrix V0  

[[ 0.47143516]
 [-1.63293445]
 [ 2.14157522]]


In [33]:
##  A verification: draw 100,000 of them and see whether they have the desired moments
        
        
Z = np.ones((1000000,3))    # define Z to store the draws   
 
for i in range (1000000):
    e = np.random.randn(3,1)    
    Y = np.matmul(L,e)
    Z[i,:] = Y.T
  

CovY = np.cov(Z.T)                        # the covariance matrix estimate, 2 by 2

print(' The covariance matrix estimate of the data  \n')
print(CovY)

[[ 0.68434407 -0.03619283 -1.64719948]
 [-0.48340618  0.78529503  1.83148902]]
 The covariance matrix estimate of the data  

[[1.00182971 0.1011089  0.29946709]
 [0.1011089  1.99941373 0.49487015]
 [0.29946709 0.49487015 2.99570164]]
